INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('Mohammed', 'Ali', 'mohammed@bank.com');

INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('Sara', 'Ahmed', 'sara@bank.com');

INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('Khalid', 'Mahmoud', 'khalid@bank.com');



INSERT INTO ACCOUNTS (OWNER, BALANCE, TYPE, STATUS, CUSTOMER_ID)
VALUES ('Mohammed', 5000, 'SAVINGS', 'ACTIVE', 1);
